name: CI

env:
    CI: true

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: "shivammathur/setup-php@v2"
              with:
                php-version: "latest"
              
            - name: Composer install
              uses: "ramsey/composer-install@v2"

            - name: PHPUnit tests
              uses: php-actions/phpunit@v3
              with:
                  php_extensions: gd zip
                  configuration: phpunit.xml